<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="en_US">
<context>
    <name>ProxyPython</name>
    <message>
        <location filename="proxypython.cpp" line="121"/>
        <source>Python Initialization failed</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="proxypython.cpp" line="122"/>
        <source>On a previous start the Python Plugin failed to initialize.
Do you want to try initializing python again (at the risk of another crash)?
 Suggestion: Select &quot;no&quot;, and click the warning sign for further help.Afterwards you have to re-enable the python plugin.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="proxypython.cpp" line="173"/>
        <source>Python Proxy</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="proxypython.cpp" line="183"/>
        <source>Proxy Plugin to allow plugins written in python to be loaded</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="proxypython.cpp" line="255"/>
        <source>ModOrganizer path contains a semicolon</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="proxypython.cpp" line="257"/>
        <source>Python DLL not found</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="proxypython.cpp" line="259"/>
        <source>Invalid Python DLL</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="proxypython.cpp" line="261"/>
        <source>Initializing Python failed</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="proxypython.cpp" line="263"/>
        <location filename="proxypython.cpp" line="293"/>
        <source>invalid problem key %1</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="proxypython.cpp" line="271"/>
        <source>The path to Mod Organizer (%1) contains a semicolon. &lt;br&gt;While this is legal on NTFS drives, many softwares do not handle it correctly.&lt;br&gt;Unfortunately MO depends on libraries that seem to fall into that group.&lt;br&gt;As a result the python plugin cannot be loaded, and the only solution we canoffer is to remove the semicolon or move MO to a path without a semicolon.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="proxypython.cpp" line="282"/>
        <source>The Python plugin DLL was not found, maybe your antivirus deleted it. Re-installing MO2 might fix the problem.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="proxypython.cpp" line="285"/>
        <source>The Python plugin DLL is invalid, maybe your antivirus is blocking it. Re-installing MO2 and adding exclusions for it to your AV might fix the problem.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="proxypython.cpp" line="290"/>
        <source>The initialization of the Python plugin DLL failed, unfortunately without any details.</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>QObject</name>
    <message>
        <location filename="../runner/error.h" line="75"/>
        <source>An unknown exception was thrown in python code.</source>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
